### ISSUE TITLE
Why are you comment-out?

### ISSUE THREAD

**Issue by zak1ck** [muukis/l4dstats#16]
Why are you comment-out here?https://github.com/muukis/l4dstats/blob/98d8f50adacee3cfeb4ea1926ac64d7a4fe0d8fd/WEBSTATS/soap/index.php#L210

**Comment by muukis** [comment]
I believe that was left in accidentally? I don't remember what I was thinking there. That should most definitely use the variables instead of the hard coded values. Thank you for looking in and bringing this to me. 👍

**Comment by zak1ck** [comment]
Oh, yeah...
Thank you for answering and fixing :)

I close this issue.
