### ISSUE TITLE
new syntax

### ISSUE THREAD

**Issue by maclarens** [muukis/l4dstats#20]
Hello!this plugin great and can u update him on 1.11 syntax becaose too many depracted codes and not working some functions

**Comment by muukis** [comment]
It can be triggered only manually from the rank menu options (as an administrator) if I remember correctly. That part of code should reply to your chat if successful or not, when you trigger it from the rank menu.

Can you tell me how do you expect it to work? Am I forgetting something? :)

**Comment by muukis** [comment]
I think that functionality is working as intended. I don't think there is an autocleaner functionality.

If you want such a feature, I would read [this tutoria](https://www.mysqltutorial.org/mysql-triggers/working-mysql-scheduled-event/)l on how to create scheduled events on MySQL database. Using that functionality, you can delete old players for instance once per day.

**Comment by maclarens** [comment]
got it thx
